print("Welcome to mystery libs")

thing = input("Enter a thing you do: ")
fill = input("Enter a thing you could fill: ")
person = input("Enter a type of person: ")
name = input ("Enter a persons name: ")
do = input ("Enter a verb (eg cry): ")
say = input ("Enter a thing you would say: ")
movement = input ("Enter a way you could move: ")

print("Get rickrolled")
print("We're no strangers to " + thing )
print("You know the rules, and so do I")
print("A full " + fill + " is what I'm thinking of")
print("You wouldn't get this from any other " + person )
print("I just wanna tell " + name + " how I'm feeling")
print("Gotta make you understand")
print("Never gonna give you up " )
print("Never gonna let you down ")
print("Never gonna " + movement + " around and desert you ")
print("Never gonna make you " + do )
print("Never gonna say " + say )
print("Never gonna tell a lie and hurt you")