name = input("enter a name")
singer = input(


    print ("Once upon a younger year")
print ("When all our shadows disappeared")
print ("The animals inside came out to play")
print ("Went face to face with all our fears")
print ("Learned our lessons through the tears")
print ("Made memories we knew would never fade")
print ("One day, my father, he told me, Son, don't let it slip away")
print ("He took me in his arms, I heard him say")
print ("When you get older your wild heart will live for younger days")
print ("Think of me if ever you're afraid")
print ("He said, One day, you'll leave this world behind")
print ("So live a life you will remember")
print ("My father told me when I was just a child")
print ("These are the nights that never die")
print ("My father told me")
print ("When thunderclouds start pouring down")
print ("Light a fire they can't put out")
print ("Carve your name into those shining stars")
print ("He said, Go venture far beyond the shores")
print ("Dont forsake this life of yours")
print ("I'll guide you home no matter where you are")
print ("One day, my father, he told me, Son, don't let it slip away")
print ("When I was just a kid, I heard him say")
print ("When you get older your wild heart will live for younger days")
print ("Think of me if ever you're afraid")
print ("He said, One day, you'll leave this world behind")
print ("So live a life you will remember")
print ("My father told me when I was just a child")
print ("These are the nights that never die")
print ("My father told me")
print ("These are the nights that never die")
print ("My father told me")
print ("My father told me")