print('Welcome to football career - Answer the following questions the create your football career')

player_name = input('enter your players name:')
football_team = input('enter your football club:')
goals_in_career = input('enter the amount of goals you have scored:')
assists_in_career = input('enter your assists:')
career_last = input('how long did your career last:')
time_played = input('what year did you start playing football:')
money = input('how much money did you make')
streamer_name = input('your youtube channel name')

print('-----START YOUR CAREER-----')
print('their was a footballer called, ' + player_name)
print('he started his career in, ' + time_played)
print('he made £' + money)
print('he scored ' + goals_in_career + ' in his career')
print('and he had ' + assists_in_career + ' assists in his career')
print('his career lasted ' + career_last + ' years')
print('he was the best player of all time and is now a youtuber that plays fifa by the name of ' + streamer_name)

