print("Welcome to Queen - Answer the following questions to create your capaldi libs")

name = input("Enter a person's name:")
call_someone = input("Enter something that you call someone :")
planets = input("Enter a planets: ")

sport= input("Enter a sport: ")
call_someone = input("Enter something that you call someone :")

print("-------Queen STARTS--------")
print("We are the" + call_someone + "my friends")
print(" And we'll keep on fighting till the end")
print(" We are the champions")
print("we aere the champions")
print("No time for losers")
print("'Cause we are the champions of the " +planets + ")
print("I've taken my some thing you do at the end And my curtain calls")
print("You brought me fame and fortune")
print("And everything that goes with anything I thank you all  ")
print("But it's been no bed of  a type of No pleasure cruise")
print("I consider it a challenge before time of day ")
print("The human" +sport+")
print("And I ain't gonna lose")
print("And we mean to go on and on and on and on")
print("We are the my friends")
print("And we'll keep on fighting till the time of the day ")
print("We are the " + call_someone +")