print('Welcome to libs star')
Name1 = input('Type in a name:')
Name2 = input ('Type in another name:')
object1 = input ('Type in a object(singular):')
verb1 = input ('Type in a verb(a doing word):')
object2 = ('Type in a object(singular):')
object3 = ('Type in another object(singular):')
Name3 = ('Type in another name:')
adj1 = ('Type in a adjective (a describing word):')
L = input ('Type in a object ')
verb2 = input('Type in a verb (A doing word):')
verb3 = input('Type in a verb (A doing word):')
verb4 = input('Type in a verb (A doing word):')
verb5 = input('Type in a verb (A doing word):')
verb6 = input('Type in a verb (A doing word):')



print(Name1 +" once told " + Name2 + " the " + object1 +" is gonna " + verb1 +" me")
print("	I ain't the sharpest " +object1 +" in the shed	")
print("	She was looking kind of dumb with her finger and her thumb")
print("	In the shape of an "+L+" on her forehead	")

print("	[Pre-Chorus]")
print("	Well, the years start comin' and they don't stop comin'")
print("	Fed to the rules and I hit the ground runnin'")
print("	Didn't make sense not to live for fun")
print("	Your brain gets smart but your head gets dumb")
print("	So much to do, so much to see")
print("	So what's wrong with")
print('taking the backstreets?')
print('Youll never know if you dont go')
print('Youll never shine if you dont glow')