# Mr Walker's feedback
# Good start and use of input, would be nice to see some use of concatenation

# Have a think about what variables you would use in your song, such as:
country1 = input("Please enter a country: ")
country2 = input("Please enter a second country: ")
country3 = input("Please enter a third country: ")

name = input("enter a name:")
singer = input("enter a singer:")
location = input("enter a country:")
animal = input("enter a animal:")
school = input("enter a school:")

print("Let’s Go")
print("Everybody Rise Up")
print("Stand Up")
print("It’s That Time")
print("Come On")

# You can then use the countries inputted above in your code (This is concatenation)
print("We Got Portugal")
print("We Got" + country1 + ", France, " + country2 + country3)
print("Belgium, Qatar, Germany")
print("U.S.A, Iran, Canada")
print("Argentina, Australia")
print("Croatia, Switzerland, Ghana, Japan")
print("Uruguay, Morocco, Saudi Arabia")
print("Ecuador, Wales, Poland, Tunisia")
print("Cameroon, Serbia, Korea")
print("Netherlands, Senegal, Costa Rica")
print("Let’s Play Football")

print("World Cup (Uh), World Cup Uh")
print("World Cup (Uh), World Cup Uh")
print("World Cup (Uh), World Cup Uh")
print("World Cup (Uh), World Cup Uh")
print("World Cup (Uh), It’s Time To Play Football Uh")
print("World Cup (Uh), It’s Time To Play Football Uh")
print("World Cup (Uh), World Cup Uh")
print("World Cup (Uh), World Cup Uh")
print("Arf, arf, arf, arf (Uh, ayy")
print("Hell nah, man, let's get right, got Portugal with come with nightlight")
print("Mexico, we come with the right")
print("Italy, yeah, we come with right, like")
print("Cameroon, we came with the pipe")
print("Mexico, wе come in right, like")
print("World Cup time, fight t-'til wе die")
print("We up-up in the field, we finna hit 'til we die")
print("Kick t-'til we die, hunt until we die")
print("Headers until we die and like hattricks, we finna try")
print("Hey, hold on, who finna win? Twenty-two, we on the bar")
print("World Cup and that Q-tar, you know we hoppin' on the jet, hah")
print("Mexico, we up in there, got a lil', for my fans, like")
