print("it was a")
adjective = input ("enter an adjective")
print("cold November day,I woke up to the")
adjective = input ("enter an adjective")
print("smell of")
type of bird = input ("enter a type of bird")
print(roasting in the")
room in a house = input("enter a room in a house")
print("downstairs.I")
verb = input ("enter a verb")
print("down the stairs to see if I could help")
verb = input ("enter a verb")
print("the dinner.My mum said,"See if")
relative's name = input ("enter a relative's name")
print("needs a fresh")
noun = input ("enter a noun")
print("So I carried a tray of glasses full of")
a liquid = input ("enter a liquid")
print("into the")
verb ending in -ing = input ("enter a verb ending in -ing")
print("room.When I got there,I couldn't believy my")
part of the body = input ("enter a par of the body")
print("!There were")
plural noun = input ("enter a plural noun")
verb ending in -ing = input ("enter a verb ending in -ing")
print("on the")
noun = input (" enter a noun")


