print("Welcome to Saint-Maximin - Answer the following questions to create your libs")

name = input("Enter a Footballers name:")
what_he_wearing = input("What is he wearin:")
name_a_place = input("Where is he from: ")
what_they_drinking = input("What are they drinking:")
who_is_his_brother = input("Who is his football brother: ")
what_number = input("What number is he: ")

print("------- LIBS START--------")
print(name)
print("On the wing")
print("And he got one man down just being him")
print("He wearin'" +  what_he_wearing)
print("So we" + what_he_wearing)
print("He got the " + name_a_place + " army drinkin " + what_they_drinking)
print("Is he a brother to " + who_is_his_brother + " We don't know yet for sure")
print("All we know, this lad is gonna give us a goal")
print("Our new number " + what_number + " is gonna flip you to the moon")
