name = input('Enter a name:')
school_subject = input('Enter a school subject:')
animal = input('Enter an animal (singular):')
location = input('Enter a city/country:')
job = input('Enter a job:')

print('------RAPLIBS START------')
print('Youre a good ' + job + ' choosing your battles')
print('Pick yourself up and dust yourself off, get back in the saddle')
print('Youre on the frontline, every ' + animal + ' watching')
print('You know its serious, were getting closer, this isnt over')
print('The pressures on, you feel it')
print('But you got it ' + name + ' believe it')
print('When you fall get up, oh, oh')
print('And if you fall get up, eh, eh')
print('Tsamina mina zangalewa cause this is ' + school_subject + '')
print('Tsamina mina, eh, eh')
print('Waka waka, eh, eh')
print('Tsamina mina zangalewa')
print('This time for ' + location + '')